# Generated by Django 5.2.8 on 2025-11-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], max_length=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fasting_required', models.BooleanField(default=False)),
                ('fasting_hours', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=255, null=True)),
                ('report_format', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('image', 'Image'), ('mixed', 'Mixed')], default='numeric', max_length=50)),
                ('tat_hours', models.IntegerField(default=24)),
                ('is_outsourced', models.BooleanField(default=False)),
                ('outsourced_lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('outsourced_lab_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('home_collection_available', models.BooleanField(default=True)),
                ('home_collection_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gender_specific', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=10)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('is_panel', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tests', to='administration.medicaltest')),
            ],
        ),
    ]
