# Generated by Django 5.2.8 on 2025-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaltest',
            old_name='machine',
            new_name='has_range',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='fasting_hours',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='home_collection_available',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='home_collection_charge',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='is_outsourced',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='is_panel',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='normal_range',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='outsourced_lab_charge',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='outsourced_lab_name',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='parent_panel',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='tat_hours',
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='Reference_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='processing_time_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text'), ('image', 'Image')], default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('saliva', 'Saliva'), ('xray', 'Xray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound')], max_length=100, null=True),
        ),
    ]
