# Generated by Django 5.2.8 on 2025-12-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_machine_medicaltest_has_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaltest',
            old_name='Reference_range',
            new_name='reference_range',
        ),
    ]
